version: '2'
services:
  cassandradb:
    container_name: cassandra
    image: cassandra:3.11.1
    restart: always
    ports:
      - "9042:9042"

  cassandra-init:
    container_name: cassandra-keyspace-init
    restart: on-failure
    build:
      context: ./docker/keyspace-init
    command: /bin/bash -c "echo Waiting for cassandra... && sleep 40 && echo loading cassandra keyspace && cqlsh cassandra -f /keyspaces.cql"

  mongodb:
    container_name: mongodb
    restart: on-failure
    image: library/mongo:4.4.0
    ports:
    - "27017:27017"
